version: '3.8'

services:
  backend:
    build: ./backend
    container_name: codefit-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mysql
    networks:
      - codefit-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/codefit?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=MyStrongPassword!
      - SPRING_REDIS_HOST=redis
      - JWT_SECRET=UoV57Qy9rhdLgPK2uX1JMwZkEfiBA6lOYZmR3HjF8atWDnpCbV4SxGTqsKuNce0y

  frontend:
    build: ./frontend
    container_name: codefit-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - codefit-network

  redis:
    image: redis:7-alpine
    container_name: codefit-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - codefit-network

  mysql:
    image: mysql:8.0
    container_name: codefit-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=MyStrongPassword!
      - MYSQL_DATABASE=codefit
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - codefit-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    hostname: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - codefit-network

volumes:
  redis_data:
    driver: local
  mysql_data:
    driver: local

networks:
  codefit-network:
    driver: bridge